### ISSUE TITLE
Nats::Server shouldn't be called that way

### ISSUE THREAD

**Issue by FCO** [FCO/nats#1]
It's not a server, it shouldn't be called that way, maybe something like:
- Nats::Client
- Nats::Connection
- Nats::Service

**Comment by FCO** [comment]
Usage example for that class: https://github.com/FCO/nats/blob/3f943f1c4d684fd2cd67c1b87f740406a429b547/examples/cro-like.raku#L17

**Comment by dontlaugh** [comment]
There are many official clients, so really you ought to follow their lead.

I would not call this "Server". Perhaps `Subscriber` or `Subscription`. Unless you intend to totally re-implement `nats-server`, everything here is a client concern.

It's confusing at first, because EVERYTHING is a client, except the NATS server itself.

**Comment by dontlaugh** [comment]
https://github.com/nats-io/nats.deno/blob/main/examples/nats-sub.ts#L61-L64 example

Note that the official NATS libraries expose multiple APIs that do the same thing, but at different levels of detail.

Consider this:
https://github.com/nats-io/nats.go/blob/main/examples/nats-sub/main.go#L99-L110

The [`Conn` object](https://github.com/nats-io/nats.go/blob/main/nats.go#L518) has a high-level subscribe method that accepts a callback.

But while that example throws away the `*Subscription` object, be aware that `Subscription` exposes an iterator-style API for getting messages as well (lower level with more control) https://github.com/nats-io/nats.go/blob/main/nats.go#L4517

After some thought, I think you should rework it as the `Connection` class and this method: https://github.com/nats-io/nats.go/blob/main/nats.go#L4083

**Comment by FCO** [comment]
I’ve renamed Nats::Server to Nats::Client and also renamed Nats::Route to Nats::Subscriptions (there is already a Nats::Subscription).
